/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gnome.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

static GnomeUIInfo datei1_menu_uiinfo[] =
{
  GNOMEUIINFO_MENU_OPEN_ITEM (on__ffnen1_activate, NULL),
  GNOMEUIINFO_MENU_SAVE_ITEM (on_speichern1_activate, NULL),
  GNOMEUIINFO_MENU_SAVE_AS_ITEM (on_speichern_unter1_activate, NULL),
  GNOMEUIINFO_SEPARATOR,
  GNOMEUIINFO_MENU_EXIT_ITEM (on_MainWindow_destroy_event, NULL),
  GNOMEUIINFO_END
};

static GnomeUIInfo hilfe1_menu_uiinfo[] =
{
  GNOMEUIINFO_MENU_ABOUT_ITEM (on_info1_activate, NULL),
  GNOMEUIINFO_END
};

static GnomeUIInfo menubar1_uiinfo[] =
{
  GNOMEUIINFO_MENU_FILE_TREE (datei1_menu_uiinfo),
  GNOMEUIINFO_MENU_HELP_TREE (hilfe1_menu_uiinfo),
  GNOMEUIINFO_END
};

GtkWidget *entry_w1;
GtkWidget *entry_w2;
GtkWidget *entry_w3;
GtkWidget *entry_r1;
GtkWidget *entry_s1;
GtkWidget *entry_r2;
GtkWidget *entry_s2;
GtkWidget *entry_r3;
GtkWidget *entry_s3;
GtkWidget *entry_stecker;
GtkWidget *entry_in;
GtkWidget *entry_out;
GtkWidget *checkbutton_animation;
GtkWidget *checkbutton_e_file;
GtkWidget *checkbutton_a_file;
GtkWidget *button_e_file;
GtkWidget *button_a_file;

GtkWidget*
create_MainWindow (void)
{
  GtkWidget *MainWindow;
  GtkWidget *vbox1;
  GtkWidget *handlebox1;
  GtkWidget *menubar1;
  gchar *pixmap_enigma_filename;
  GtkWidget *pixmap_enigma;
  GtkWidget *notebook1;
  GtkWidget *table1;
  GtkWidget *label4;
  GtkWidget *label5;
  GtkWidget *label6;
  GtkWidget *label7;
  GtkWidget *label8;
  GtkWidget *label9;
  GtkWidget *label10;
  GtkWidget *label11;
  GtkWidget *label12;
  GtkWidget *label13;
  GtkWidget *Einstellungen;
  GtkWidget *vbox2;
  GtkWidget *frame1;
  GtkWidget *button_calc;
  GtkWidget *frame2;
  GtkWidget *label2;
  GtkWidget *hbox1;
  GtkWidget *hbox2;
  GtkWidget *Optionen;

  MainWindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (MainWindow, "MainWindow");
  gtk_object_set_data (GTK_OBJECT (MainWindow), "MainWindow", MainWindow);
  gtk_window_set_title (GTK_WINDOW (MainWindow), _("genigma"));
  gtk_window_set_policy (GTK_WINDOW (MainWindow), FALSE, TRUE, TRUE);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox1, "vbox1");
  gtk_widget_ref (vbox1);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "vbox1", vbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (MainWindow), vbox1);

  handlebox1 = gtk_handle_box_new ();
  gtk_widget_set_name (handlebox1, "handlebox1");
  gtk_widget_ref (handlebox1);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "handlebox1", handlebox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (handlebox1);
  gtk_box_pack_start (GTK_BOX (vbox1), handlebox1, FALSE, FALSE, 0);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_set_name (menubar1, "menubar1");
  gtk_widget_ref (menubar1);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "menubar1", menubar1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (menubar1);
  gtk_container_add (GTK_CONTAINER (handlebox1), menubar1);
  gnome_app_fill_menu (GTK_MENU_SHELL (menubar1), menubar1_uiinfo,
                       NULL, FALSE, 0);

  gtk_widget_set_name (menubar1_uiinfo[0].widget, "datei1");
  gtk_widget_ref (menubar1_uiinfo[0].widget);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "datei1",
                            menubar1_uiinfo[0].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_set_name (datei1_menu_uiinfo[0].widget, "_ffnen1");
  gtk_widget_ref (datei1_menu_uiinfo[0].widget);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "_ffnen1",
                            datei1_menu_uiinfo[0].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_set_name (datei1_menu_uiinfo[1].widget, "speichern1");
  gtk_widget_ref (datei1_menu_uiinfo[1].widget);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "speichern1",
                            datei1_menu_uiinfo[1].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_set_name (datei1_menu_uiinfo[2].widget, "speichern_unter1");
  gtk_widget_ref (datei1_menu_uiinfo[2].widget);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "speichern_unter1",
                            datei1_menu_uiinfo[2].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_set_name (datei1_menu_uiinfo[3].widget, "separator1");
  gtk_widget_ref (datei1_menu_uiinfo[3].widget);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "separator1",
                            datei1_menu_uiinfo[3].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_set_name (datei1_menu_uiinfo[4].widget, "beenden1");
  gtk_widget_ref (datei1_menu_uiinfo[4].widget);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "beenden1",
                            datei1_menu_uiinfo[4].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_set_name (menubar1_uiinfo[1].widget, "hilfe1");
  gtk_widget_ref (menubar1_uiinfo[1].widget);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "hilfe1",
                            menubar1_uiinfo[1].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_set_name (hilfe1_menu_uiinfo[0].widget, "info1");
  gtk_widget_ref (hilfe1_menu_uiinfo[0].widget);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "info1",
                            hilfe1_menu_uiinfo[0].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  pixmap_enigma = gtk_type_new (gnome_pixmap_get_type ());
  pixmap_enigma_filename = gnome_pixmap_file ("genigma/enigma2.jpg");
  if (pixmap_enigma_filename)
    gnome_pixmap_load_file (GNOME_PIXMAP (pixmap_enigma), pixmap_enigma_filename);
  else
    g_warning (_("Couldn't find pixmap file: %s"), "enigma2.jpg");
  g_free (pixmap_enigma_filename);
  gtk_widget_set_name (pixmap_enigma, "pixmap_enigma");
  gtk_widget_ref (pixmap_enigma);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pixmap_enigma", pixmap_enigma,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap_enigma);
  gtk_box_pack_start (GTK_BOX (vbox1), pixmap_enigma, TRUE, TRUE, 0);

  notebook1 = gtk_notebook_new ();
  gtk_widget_set_name (notebook1, "notebook1");
  gtk_widget_ref (notebook1);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "notebook1", notebook1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (notebook1);
  gtk_box_pack_start (GTK_BOX (vbox1), notebook1, TRUE, TRUE, 0);

  table1 = gtk_table_new (4, 6, FALSE);
  gtk_widget_set_name (table1, "table1");
  gtk_widget_ref (table1);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "table1", table1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table1);
  gtk_container_add (GTK_CONTAINER (notebook1), table1);
  gtk_container_set_border_width (GTK_CONTAINER (table1), 3);
  gtk_table_set_row_spacings (GTK_TABLE (table1), 2);
  gtk_table_set_col_spacings (GTK_TABLE (table1), 2);

  label4 = gtk_label_new (_("Walze 1:"));
  gtk_widget_set_name (label4, "label4");
  gtk_widget_ref (label4);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "label4", label4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label4);
  gtk_table_attach (GTK_TABLE (table1), label4, 0, 1, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  label5 = gtk_label_new (_("Walze 2:"));
  gtk_widget_set_name (label5, "label5");
  gtk_widget_ref (label5);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "label5", label5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label5);
  gtk_table_attach (GTK_TABLE (table1), label5, 2, 3, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  label6 = gtk_label_new (_("Walze 3:"));
  gtk_widget_set_name (label6, "label6");
  gtk_widget_ref (label6);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "label6", label6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label6);
  gtk_table_attach (GTK_TABLE (table1), label6, 4, 5, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  entry_w1 = gtk_entry_new_with_max_length (1);
  gtk_widget_set_name (entry_w1, "entry_w1");
  gtk_widget_ref (entry_w1);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "entry_w1", entry_w1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry_w1);
  gtk_table_attach (GTK_TABLE (table1), entry_w1, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_usize (entry_w1, 25, -2);
  gtk_entry_set_text (GTK_ENTRY (entry_w1), _("1"));

  entry_w2 = gtk_entry_new_with_max_length (1);
  gtk_widget_set_name (entry_w2, "entry_w2");
  gtk_widget_ref (entry_w2);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "entry_w2", entry_w2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry_w2);
  gtk_table_attach (GTK_TABLE (table1), entry_w2, 3, 4, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_usize (entry_w2, 25, -2);
  gtk_entry_set_text (GTK_ENTRY (entry_w2), _("2"));

  entry_w3 = gtk_entry_new_with_max_length (1);
  gtk_widget_set_name (entry_w3, "entry_w3");
  gtk_widget_ref (entry_w3);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "entry_w3", entry_w3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry_w3);
  gtk_table_attach (GTK_TABLE (table1), entry_w3, 5, 6, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_usize (entry_w3, 25, -2);
  gtk_entry_set_text (GTK_ENTRY (entry_w3), _("3"));

  label7 = gtk_label_new (_("Ring 1:"));
  gtk_widget_set_name (label7, "label7");
  gtk_widget_ref (label7);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "label7", label7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label7);
  gtk_table_attach (GTK_TABLE (table1), label7, 0, 1, 1, 2,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  label8 = gtk_label_new (_("Ring 2:"));
  gtk_widget_set_name (label8, "label8");
  gtk_widget_ref (label8);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "label8", label8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label8);
  gtk_table_attach (GTK_TABLE (table1), label8, 2, 3, 1, 2,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  label9 = gtk_label_new (_("Ring 3:"));
  gtk_widget_set_name (label9, "label9");
  gtk_widget_ref (label9);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "label9", label9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label9);
  gtk_table_attach (GTK_TABLE (table1), label9, 4, 5, 1, 2,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  label10 = gtk_label_new (_("Start 1:"));
  gtk_widget_set_name (label10, "label10");
  gtk_widget_ref (label10);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "label10", label10,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label10);
  gtk_table_attach (GTK_TABLE (table1), label10, 0, 1, 2, 3,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  label11 = gtk_label_new (_("Start 2:"));
  gtk_widget_set_name (label11, "label11");
  gtk_widget_ref (label11);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "label11", label11,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label11);
  gtk_table_attach (GTK_TABLE (table1), label11, 2, 3, 2, 3,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  label12 = gtk_label_new (_("Start 3:"));
  gtk_widget_set_name (label12, "label12");
  gtk_widget_ref (label12);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "label12", label12,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label12);
  gtk_table_attach (GTK_TABLE (table1), label12, 4, 5, 2, 3,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  label13 = gtk_label_new (_("Stecker:"));
  gtk_widget_set_name (label13, "label13");
  gtk_widget_ref (label13);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "label13", label13,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label13);
  gtk_table_attach (GTK_TABLE (table1), label13, 0, 1, 3, 4,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  entry_r1 = gtk_entry_new_with_max_length (1);
  gtk_widget_set_name (entry_r1, "entry_r1");
  gtk_widget_ref (entry_r1);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "entry_r1", entry_r1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry_r1);
  gtk_table_attach (GTK_TABLE (table1), entry_r1, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_usize (entry_r1, 25, -2);
  gtk_entry_set_text (GTK_ENTRY (entry_r1), _("A"));

  entry_s1 = gtk_entry_new_with_max_length (1);
  gtk_widget_set_name (entry_s1, "entry_s1");
  gtk_widget_ref (entry_s1);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "entry_s1", entry_s1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry_s1);
  gtk_table_attach (GTK_TABLE (table1), entry_s1, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_usize (entry_s1, 25, -2);
  gtk_entry_set_text (GTK_ENTRY (entry_s1), _("A"));

  entry_r2 = gtk_entry_new_with_max_length (1);
  gtk_widget_set_name (entry_r2, "entry_r2");
  gtk_widget_ref (entry_r2);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "entry_r2", entry_r2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry_r2);
  gtk_table_attach (GTK_TABLE (table1), entry_r2, 3, 4, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_usize (entry_r2, 25, -2);
  gtk_entry_set_text (GTK_ENTRY (entry_r2), _("A"));

  entry_s2 = gtk_entry_new_with_max_length (1);
  gtk_widget_set_name (entry_s2, "entry_s2");
  gtk_widget_ref (entry_s2);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "entry_s2", entry_s2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry_s2);
  gtk_table_attach (GTK_TABLE (table1), entry_s2, 3, 4, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_usize (entry_s2, 25, -2);
  gtk_entry_set_text (GTK_ENTRY (entry_s2), _("A"));

  entry_r3 = gtk_entry_new_with_max_length (1);
  gtk_widget_set_name (entry_r3, "entry_r3");
  gtk_widget_ref (entry_r3);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "entry_r3", entry_r3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry_r3);
  gtk_table_attach (GTK_TABLE (table1), entry_r3, 5, 6, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_usize (entry_r3, 25, -2);
  gtk_entry_set_text (GTK_ENTRY (entry_r3), _("A"));

  entry_s3 = gtk_entry_new_with_max_length (1);
  gtk_widget_set_name (entry_s3, "entry_s3");
  gtk_widget_ref (entry_s3);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "entry_s3", entry_s3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry_s3);
  gtk_table_attach (GTK_TABLE (table1), entry_s3, 5, 6, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_usize (entry_s3, 25, -2);
  gtk_entry_set_text (GTK_ENTRY (entry_s3), _("A"));

  entry_stecker = gtk_entry_new_with_max_length (26);
  gtk_widget_set_name (entry_stecker, "entry_stecker");
  gtk_widget_ref (entry_stecker);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "entry_stecker", entry_stecker,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry_stecker);
  gtk_table_attach (GTK_TABLE (table1), entry_stecker, 1, 6, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  Einstellungen = gtk_label_new (_("Einstellungen"));
  gtk_widget_set_name (Einstellungen, "Einstellungen");
  gtk_widget_ref (Einstellungen);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "Einstellungen", Einstellungen,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Einstellungen);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), Einstellungen);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox2, "vbox2");
  gtk_widget_ref (vbox2);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "vbox2", vbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (notebook1), vbox2);
  gtk_container_set_border_width (GTK_CONTAINER (vbox2), 4);

  frame1 = gtk_frame_new (_("Eingabe"));
  gtk_widget_set_name (frame1, "frame1");
  gtk_widget_ref (frame1);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "frame1", frame1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame1);
  gtk_box_pack_start (GTK_BOX (vbox2), frame1, TRUE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame1), GTK_SHADOW_ETCHED_OUT);

  entry_in = gtk_entry_new ();
  gtk_widget_set_name (entry_in, "entry_in");
  gtk_widget_ref (entry_in);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "entry_in", entry_in,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry_in);
  gtk_container_add (GTK_CONTAINER (frame1), entry_in);

  button_calc = gtk_button_new_with_label (_("Rechne"));
  gtk_widget_set_name (button_calc, "button_calc");
  gtk_widget_ref (button_calc);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "button_calc", button_calc,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button_calc);
  gtk_box_pack_start (GTK_BOX (vbox2), button_calc, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (button_calc), 3);

  frame2 = gtk_frame_new (_("Ausgabe"));
  gtk_widget_set_name (frame2, "frame2");
  gtk_widget_ref (frame2);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "frame2", frame2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame2);
  gtk_box_pack_start (GTK_BOX (vbox2), frame2, TRUE, TRUE, 0);

  entry_out = gtk_entry_new ();
  gtk_widget_set_name (entry_out, "entry_out");
  gtk_widget_ref (entry_out);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "entry_out", entry_out,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry_out);
  gtk_container_add (GTK_CONTAINER (frame2), entry_out);
  gtk_entry_set_editable (GTK_ENTRY (entry_out), FALSE);

  label2 = gtk_label_new (_("Enigma"));
  gtk_widget_set_name (label2, "label2");
  gtk_widget_ref (label2);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "label2", label2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label2);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label2);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox1, "vbox1");
  gtk_widget_ref (vbox1);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "vbox1", vbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (notebook1), vbox1);

  checkbutton_animation = gtk_check_button_new_with_label (_("Animation"));
  gtk_widget_set_name (checkbutton_animation, "checkbutton_animation");
  gtk_widget_ref (checkbutton_animation);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "checkbutton_animation", checkbutton_animation,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton_animation);
  gtk_box_pack_start (GTK_BOX (vbox1), checkbutton_animation, FALSE, FALSE, 0);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (checkbutton_animation), TRUE);
  gtk_widget_hide( checkbutton_animation );

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox1, "hbox1");
  gtk_widget_ref (hbox1);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "hbox1", hbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox1, FALSE, FALSE, 0);

  checkbutton_e_file = gtk_check_button_new_with_label (_("Eingabe von File"));
  gtk_widget_set_name (checkbutton_e_file, "checkbutton_e_file");
  gtk_widget_ref (checkbutton_e_file);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "checkbutton_e_file", checkbutton_e_file,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton_e_file);
  gtk_box_pack_start (GTK_BOX (hbox1), checkbutton_e_file, FALSE, FALSE, 0);

  button_e_file = gtk_button_new_with_label (_("..."));
  gtk_widget_set_name (button_e_file, "button_e_file");
  gtk_widget_ref (button_e_file);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "button_e_file", button_e_file,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button_e_file);
  gtk_box_pack_start (GTK_BOX (hbox1), button_e_file, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (button_e_file, FALSE);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox2, "hbox2");
  gtk_widget_ref (hbox2);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "hbox2", hbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox2, FALSE, TRUE, 0);

  checkbutton_a_file = gtk_check_button_new_with_label (_("Ausgabe auf File"));
  gtk_widget_set_name (checkbutton_a_file, "checkbutton_a_file");
  gtk_widget_ref (checkbutton_a_file);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "checkbutton_a_file", checkbutton_a_file,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton_a_file);
  gtk_box_pack_start (GTK_BOX (hbox2), checkbutton_a_file, FALSE, FALSE, 0);

  button_a_file = gtk_button_new_with_label (_("..."));
  gtk_widget_set_name (button_a_file, "button_a_file");
  gtk_widget_ref (button_a_file);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "button_a_file", button_a_file,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button_a_file);
  gtk_box_pack_start (GTK_BOX (hbox2), button_a_file, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (button_a_file, FALSE);

  Optionen = gtk_label_new (_("Optionen"));
  gtk_widget_set_name (Optionen, "Optionen");
  gtk_widget_ref (Optionen);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "Optionen", Optionen,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Optionen);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), Optionen);

  gtk_signal_connect (GTK_OBJECT (MainWindow), "destroy_event",
                      GTK_SIGNAL_FUNC (on_MainWindow_destroy_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (MainWindow), "delete_event",
                      GTK_SIGNAL_FUNC (on_MainWindow_destroy_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (entry_in), "activate",
                      GTK_SIGNAL_FUNC (on_entry_in_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button_calc), "clicked",
                      GTK_SIGNAL_FUNC (on_button_calc_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (checkbutton_e_file), "toggled",
                      GTK_SIGNAL_FUNC (on_checkbutton_e_file_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button_e_file), "clicked",
                      GTK_SIGNAL_FUNC (on_button_e_file_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (checkbutton_a_file), "toggled",
                      GTK_SIGNAL_FUNC (on_checkbutton_a_file_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button_a_file), "clicked",
                      GTK_SIGNAL_FUNC (on_button_a_file_clicked),
                      NULL);

  return MainWindow;
}

GtkWidget*
create_about1 (void)
{
  const gchar *authors[] = {
    "Martin Oberzalek",
    NULL
  };
  GtkWidget *about1;

  about1 = gnome_about_new ("genigma", VERSION,
                        _("(C) 2000 Martin Oberzalek"),
                        authors,
                        _("Eine Emulation der brühmten Enigma.\nKommentare an leo@checkitmail.at"),
                        "genigma/logo1.png");
  gtk_widget_set_name (about1, "about1");
  gtk_object_set_data (GTK_OBJECT (about1), "about1", about1);
  gtk_window_set_modal (GTK_WINDOW (about1), TRUE);

  return about1;
}

GtkWidget*
create_messagebox_stecker (void)
{
  GtkWidget *messagebox_stecker;
  GtkWidget *dialog_vbox1;
  GtkWidget *button1;
  GtkWidget *dialog_action_area1;

  messagebox_stecker = gnome_message_box_new (_("Der Stecker ist ungültig!\nJeder Buchstabe darf nur einmal verwendet\nwerden und es ist nur eine gerade Anzahl von \nBuchstaben zulässig."),
                              GNOME_MESSAGE_BOX_ERROR, NULL);
  gtk_widget_set_name (messagebox_stecker, "messagebox_stecker");
  gtk_object_set_data (GTK_OBJECT (messagebox_stecker), "messagebox_stecker", messagebox_stecker);
  gtk_window_set_policy (GTK_WINDOW (messagebox_stecker), FALSE, FALSE, FALSE);
  gnome_dialog_set_close (GNOME_DIALOG (messagebox_stecker), TRUE);

  dialog_vbox1 = GNOME_DIALOG (messagebox_stecker)->vbox;
  gtk_widget_set_name (dialog_vbox1, "dialog_vbox1");
  gtk_object_set_data (GTK_OBJECT (messagebox_stecker), "dialog_vbox1", dialog_vbox1);
  gtk_widget_show (dialog_vbox1);

  gnome_dialog_append_button (GNOME_DIALOG (messagebox_stecker), GNOME_STOCK_BUTTON_OK);
  button1 = g_list_last (GNOME_DIALOG (messagebox_stecker)->buttons)->data;
  gtk_widget_set_name (button1, "button1");
  gtk_widget_ref (button1);
  gtk_object_set_data_full (GTK_OBJECT (messagebox_stecker), "button1", button1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button1);
  GTK_WIDGET_SET_FLAGS (button1, GTK_CAN_DEFAULT);

  dialog_action_area1 = GNOME_DIALOG (messagebox_stecker)->action_area;
  if (dialog_action_area1 != NULL)
    gtk_widget_set_name (dialog_action_area1, "dialog_action_area1");
  gtk_widget_ref (dialog_action_area1);
  gtk_object_set_data_full (GTK_OBJECT (messagebox_stecker), "dialog_action_area1", dialog_action_area1,
                            (GtkDestroyNotify) gtk_widget_unref);

  return messagebox_stecker;
}

GtkWidget*
create_messagebox_walzen (void)
{
  GtkWidget *messagebox_walzen;
  GtkWidget *dialog_vbox2;
  GtkWidget *button2;
  GtkWidget *dialog_action_area2;

  messagebox_walzen = gnome_message_box_new (_("Die Walzeneinträge sind ungültig!\nEs stehen 5 Walzen zur Verfügung die in\nbeliebiger Reihenfolge eingesetzt werden\nkönnen.\nSomit sind nur Zahlen zwischen 1 und 5 \ngültig."),
                              GNOME_MESSAGE_BOX_ERROR, NULL);
  gtk_widget_set_name (messagebox_walzen, "messagebox_walzen");
  gtk_object_set_data (GTK_OBJECT (messagebox_walzen), "messagebox_walzen", messagebox_walzen);
  gtk_window_set_policy (GTK_WINDOW (messagebox_walzen), FALSE, FALSE, FALSE);
  gnome_dialog_set_close (GNOME_DIALOG (messagebox_walzen), TRUE);

  dialog_vbox2 = GNOME_DIALOG (messagebox_walzen)->vbox;
  gtk_widget_set_name (dialog_vbox2, "dialog_vbox2");
  gtk_object_set_data (GTK_OBJECT (messagebox_walzen), "dialog_vbox2", dialog_vbox2);
  gtk_widget_show (dialog_vbox2);

  gnome_dialog_append_button (GNOME_DIALOG (messagebox_walzen), GNOME_STOCK_BUTTON_OK);
  button2 = g_list_last (GNOME_DIALOG (messagebox_walzen)->buttons)->data;
  gtk_widget_set_name (button2, "button2");
  gtk_widget_ref (button2);
  gtk_object_set_data_full (GTK_OBJECT (messagebox_walzen), "button2", button2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button2);
  GTK_WIDGET_SET_FLAGS (button2, GTK_CAN_DEFAULT);

  dialog_action_area2 = GNOME_DIALOG (messagebox_walzen)->action_area;
  if (dialog_action_area2 != NULL)
    gtk_widget_set_name (dialog_action_area2, "dialog_action_area2");
  gtk_widget_ref (dialog_action_area2);
  gtk_object_set_data_full (GTK_OBJECT (messagebox_walzen), "dialog_action_area2", dialog_action_area2,
                            (GtkDestroyNotify) gtk_widget_unref);

  return messagebox_walzen;
}

GtkWidget*
create_messagebox_ring (void)
{
  GtkWidget *messagebox_ring;
  GtkWidget *dialog_vbox3;
  GtkWidget *button3;
  GtkWidget *dialog_action_area3;

  messagebox_ring = gnome_message_box_new (_("Die Ringstellung ist ungültig!\nEs dürfen nur die Buchstaben A bis Z\nverwendet werden."),
                              GNOME_MESSAGE_BOX_ERROR, NULL);
  gtk_widget_set_name (messagebox_ring, "messagebox_ring");
  gtk_object_set_data (GTK_OBJECT (messagebox_ring), "messagebox_ring", messagebox_ring);
  gtk_window_set_policy (GTK_WINDOW (messagebox_ring), FALSE, FALSE, FALSE);
  gnome_dialog_set_close (GNOME_DIALOG (messagebox_ring), TRUE);

  dialog_vbox3 = GNOME_DIALOG (messagebox_ring)->vbox;
  gtk_widget_set_name (dialog_vbox3, "dialog_vbox3");
  gtk_object_set_data (GTK_OBJECT (messagebox_ring), "dialog_vbox3", dialog_vbox3);
  gtk_widget_show (dialog_vbox3);

  gnome_dialog_append_button (GNOME_DIALOG (messagebox_ring), GNOME_STOCK_BUTTON_OK);
  button3 = g_list_last (GNOME_DIALOG (messagebox_ring)->buttons)->data;
  gtk_widget_set_name (button3, "button3");
  gtk_widget_ref (button3);
  gtk_object_set_data_full (GTK_OBJECT (messagebox_ring), "button3", button3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button3);
  GTK_WIDGET_SET_FLAGS (button3, GTK_CAN_DEFAULT);

  dialog_action_area3 = GNOME_DIALOG (messagebox_ring)->action_area;
  if (dialog_action_area3 != NULL)
    gtk_widget_set_name (dialog_action_area3, "dialog_action_area3");
  gtk_widget_ref (dialog_action_area3);
  gtk_object_set_data_full (GTK_OBJECT (messagebox_ring), "dialog_action_area3", dialog_action_area3,
                            (GtkDestroyNotify) gtk_widget_unref);

  return messagebox_ring;
}

GtkWidget*
create_messagebox_start (void)
{
  GtkWidget *messagebox_start;
  GtkWidget *dialog_vbox4;
  GtkWidget *button4;
  GtkWidget *dialog_action_area4;

  messagebox_start = gnome_message_box_new (_("Die Startposition ist ungültig!\nEs dürfen nur die Buchstaben A bis Z\nverwendet werden."),
                              GNOME_MESSAGE_BOX_ERROR, NULL);
  gtk_widget_set_name (messagebox_start, "messagebox_start");
  gtk_object_set_data (GTK_OBJECT (messagebox_start), "messagebox_start", messagebox_start);
  gtk_window_set_policy (GTK_WINDOW (messagebox_start), FALSE, FALSE, FALSE);
  gnome_dialog_set_close (GNOME_DIALOG (messagebox_start), TRUE);

  dialog_vbox4 = GNOME_DIALOG (messagebox_start)->vbox;
  gtk_widget_set_name (dialog_vbox4, "dialog_vbox4");
  gtk_object_set_data (GTK_OBJECT (messagebox_start), "dialog_vbox4", dialog_vbox4);
  gtk_widget_show (dialog_vbox4);

  gnome_dialog_append_button (GNOME_DIALOG (messagebox_start), GNOME_STOCK_BUTTON_OK);
  button4 = g_list_last (GNOME_DIALOG (messagebox_start)->buttons)->data;
  gtk_widget_set_name (button4, "button4");
  gtk_widget_ref (button4);
  gtk_object_set_data_full (GTK_OBJECT (messagebox_start), "button4", button4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button4);
  GTK_WIDGET_SET_FLAGS (button4, GTK_CAN_DEFAULT);

  dialog_action_area4 = GNOME_DIALOG (messagebox_start)->action_area;
  if (dialog_action_area4 != NULL)
    gtk_widget_set_name (dialog_action_area4, "dialog_action_area4");
  gtk_widget_ref (dialog_action_area4);
  gtk_object_set_data_full (GTK_OBJECT (messagebox_start), "dialog_action_area4", dialog_action_area4,
                            (GtkDestroyNotify) gtk_widget_unref);

  return messagebox_start;
}

