/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_MainWindow (void);
GtkWidget* create_about1 (void);
GtkWidget* create_messagebox_stecker (void);
GtkWidget* create_messagebox_walzen (void);
GtkWidget* create_messagebox_ring (void);
GtkWidget* create_messagebox_start (void);
